### ISSUE TITLE
latex on some workers but not on others.. Or why does doxygen generate latex for sm_doc even though it is disabled

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/continuous_integration#52]
Apparently on the master Jenkins instances there is latex installed. On W540 it isn't. I wouldn't mind at all if not this way sm_doc (current master HEAD) fails to "build" on W540 but succeeds on the master instances.

On the other hand doxygen should not even touch latex, because it is disabled in the config file (see. https://github.com/ethz-asl/Schweizer-Messer/blob/master/sm_doc/doc/doxygen.config.in#L1020). 

So naturally to fix that would be the better option than installing latex on W540 (and maybe the Macs). 
But I have no idea how to fix it. Somebody any idea / memory what could override GENERATE_LATEX= NO? (I've checked the file on jenkins it contains that line).

See http://129.132.38.183:8080/job/SchweizerMesser/label=ubuntu/99/consoleFull for how it goes wrong, or this extract
```
/usr/bin/doxygen /var/lib/jenkins/jobs/SchweizerMesser/workspace/label/ubuntu/src/schweizer_messer/sm_doc/doc/doxygen.config
..............
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
 restricted \write18 enabled.
entering extended mode
(./_formulas.tex
LaTeX2e <2011/06/27>
Babel <3.9h> and hyphenation patterns for 78 languages loaded.
```

(btw. when I build sm_doc on my machine, no latex is used)

**Comment by HannesSommer** [comment]
@schneith , would it be fine for you to install latex on the W540 as a workaround? (not urgent)

**Comment by schneith** [comment]
Yes, no problem. I just started the installation. Is there an easy way to check whether the problem is resolved?

**Comment by schneith** [comment]
@HannesSommer Latex should be installed now.

**Comment by HannesSommer** [comment]
I've just triggered a build to test and it worked :).
Thanks a lot!
