### ISSUE TITLE
Doxygen on some of the slaves is missing latex

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/continuous_integration#66]
This leads to an error state of the build at least if Schweizer-Messer is involved (as in http://129.132.38.183:8080/job/SchweizerMesser/136/label=ubuntu/parsed_console/). 

Doxygen is using latex for html output (for formulas). Therefore it does not help that latex output is disabled. 

Is it much effort to install enough latex for that on the the-mac-mini (and mc-jenkins)?

Or shall we try to disable doxygen for Jenkins builds?

Any opinions?

**Comment by schneith** [comment]
I would say we install latex on all slaves. This is also required by the paper build jobs.

I can do that for the mc-jenkins but i don't have access to the mac-mini. @dymczykm could you do that?

**Comment by dymczykm** [comment]
@HannesSommer this is seems to be fixed, isn't it? latex command is available on macmini.

**Comment by HannesSommer** [comment]
Yes, it works now. Thanks a lot!
