### ISSUE TITLE
Launch roscor per job (if required)

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/continuous_integration#86]
Why:
 1. a permanently running `roscore` is not robust ( #51 ) and it is conceptually not able to support multiple tests in parallel
 2. it contradicts the principle of unit testing in a fresh environment because it has memory
 3. as soon as we launch individual containers per job, it will be quite a waste
 4. without that we would need to implement a specific solution for the docker slaves, which could be almost as much work

Where and how:
In principle this could already be done with the prepare script ( #79 ) on a per repository basis. 

But as this seems to be a common need we might want to directly support it through the `run_build.sh` script.
In any case we must not forget to make sure that the core dies at the end of the job.
To support multiple tests in parallel and therefore multiple roscors we need to find a way to allocate and assign individual ports. Having that things get easy: http://wiki.ros.org/roscore.

@eggerk , would you like to work on this? Or anybody else?

**Comment by eggerk** [comment]
@HannesSommer yes, I can work on it

**Comment by HannesSommer** [comment]
Awesome! Please feel free to drop by whenever you get stuck.
I would suggest adding a boolean flag to ask for a roscore right here : https://github.com/ethz-asl/continuous_integration/blob/master/run_build_impl.sh#L27-L71.

**Comment by HannesSommer** [comment]
Solved with #95 .
